size_content: 50
size_area: 150
user: 0
admin: 1
size_password: 6
per_page: 5
answer_size_default: 4
min_answers: 2
max_answers: 6
true_size_answers: 1
size_img: 50
size: 50
version: 1.0.0
per_page_words: 10
list: 25
limit_number_word: 10
per_page_users: 20

option:
  - learned
  - unlearned
  - all
